from enum import Enum

class DBEnums(str, Enum):
    COLLECTION_USER_NAME= "USERS"
    COLLECTION_RECOMENDATION_NAME = "RECOMENDATION"
    COLLECTION_SCHEDULE_NAME = "SCHEDULE"
    COLLECTION_BUSINESS_INFO_NAME = "BUISNESS_INFO"
    COLLECTION_NOTIFICATION_NAME= "NOTIFICATION"
    COLLECTION_POST_NAME= "POSTS"
    COLLECTION_ANALYTICS_NAME= "ANALYTICS"
